/*
 * tb_DIMC.sv
 *
 * PURPOSE
 * Testbench for the spatz_DIMC module (defined in spatz_DIMC.sv).
 *
 * TEST STRUCTURE
 * All stimulus (kernel weights, feature vector) and golden outputs
 * are generated by generate_stim.py before simulation.  The testbench
 * reads them at runtime with $readmemh.
 *
 * Test 5 — Reset: verify all DUT outputs and memories are zero
 * Test 1 — Kernel write + readback: 32 rows × 4 sections
 * Test 2 — Feature load: 4 × 256-bit sections into feature buffer
 * Test 3 — Full MatVec: all 32 rows, MCT=0, check psout + quant
 * Test 4 — MCT sweep: row 0 at 6 different MCT values
 *
 * ============================================================
 * TO RUN SIMULATION  
 * ============================================================
 *  make hw-clean
 *  make hw-all
 *  make sim-single
 */

// ── Test enable macros ────────────────────────────────────────────────────
// Comment out a line to skip that test at compile time.
`define TB_DIMC_TEST5    // Reset verification
`define TB_DIMC_TEST1    // Kernel write + read-back
`define TB_DIMC_TEST1B   // Optimized kernel write + read-back
`define TB_DIMC_TEST2    // Feature load
`define TB_DIMC_TEST3    // Full MatVec (requires Tests 1 and 2)
`define TB_DIMC_TEST4    // MCT masking sweep (requires Tests 1 and 2)
// ─────────────────────────────────────────────────────────────────────────

`timescale 1ns/1ps

module tb_DIMC;

  // -------------------------------------------------------------------------
  // Parameters
  // -------------------------------------------------------------------------
  // SECTION_WIDTH: each of the four memory sections is 256 bits wide.
  //   Four sections × 256 bits = 1024 bits = one full kernel row or
  //   one full feature vector.
  parameter SECTION_WIDTH  = 256;

  // NB_KERNEL_ROWS: the DUT stores 32 rows of kernel weights.
  //   Each row is 128 uint8 elements = 1024 bits = 4 × 256-bit sections.
  parameter NB_KERNEL_ROWS = 32;

  // Stimulus files produced by gen_stim.py.
  // They must be present in the simulator's working directory before
  // the simulation runs; gen_stim.py writes them to the current directory.
  parameter KERNEL_WEIGHTS_FILE        = "stimuli/kernel_weights.txt";       // File 1
  parameter FEATURE_VECTOR_FILE        = "stimuli/feature_vector.txt";       // File 2
  parameter GOLDEN_MATVEC_FILE          = "stimuli/golden_4bit.txt";         // File 3
  parameter GOLDEN_PSOUT_FILE           = "stimuli/golden_psum_24bit.txt";   // File 4
  parameter GOLDEN_DOT_PRODUCT_MCT_FILE = "stimuli/golden_mct_4bit.txt";     // File 5
  parameter GOLDEN_PSOUT_MCT_FILE       = "stimuli/golden_psum_mct_24bit.txt"; // File 6

  // NB_MCT_VALS: how many distinct MCT values are swept in Test 4.
  // Must equal len(MCT_VALS) in gen_stim.py.
  parameter NB_MCT_VALS = 6;

  localparam logic signed [23:0] BIAS = -2_080_000;

  // MCT_VALS: the six threshold values swept in Test 4.
  // Each value trims a different number of byte-elements from the computation.
  // MUST match MCT_VALS in gen_stim.py.
  localparam logic [7:0] MCT_VALS [NB_MCT_VALS] = '{8'd0, 8'd128, 8'd192, 8'd224, 8'd240, 8'd248};

  // Stimulus and golden arrays
  // These are filled by $readmemh at the start of the test sequence.
  logic [SECTION_WIDTH-1:0] kernel_stim  [0 : NB_KERNEL_ROWS*4-1];

  // feature_stim: the 1024-bit feature vector split into 4 × 256-bit sections.
  //   feature_stim[0] = bits [255:0], feature_stim[3] = bits [1023:768].
  logic [SECTION_WIDTH-1:0] feature_stim [0 : 3];

  logic [7:0]  golden_4bit  [0 : NB_KERNEL_ROWS-1];

  logic [23:0] golden_psout   [0 : NB_KERNEL_ROWS-1];

  logic [7:0]  golden_mct     [0 : NB_MCT_VALS-1];

  logic [23:0] golden_psout_mct[0 : NB_MCT_VALS-1];

  // Timing parameters
  localparam time ClkPeriod = 10ns;
  localparam time ApplTime  =  2ns;
  localparam time TestTime  =  8ns;
  localparam NUM_SECTIONS = 1024 / SECTION_WIDTH;
  localparam ROW_WIDTH    = 1024;

  // =========================================================================
  // DUT SIGNAL DECLARATIONS
  // =========================================================================
  logic RCK;
  logic RESETn;

  logic        READYN;
  logic        COMPE  = 1'b0;
  logic        FCSN   = 1'b1;
  logic [1:0]  MODE   = 2'b11;
  
  logic [1:0]               FA    = '0;
  logic [SECTION_WIDTH-1:0] FD    = '0;
  
  logic [23:0]              ADDIN = '0;
  logic                     SOUT;

  logic [2:0]               RES_OUT;
  logic [23:0]              PSOUT;
  logic [SECTION_WIDTH-1:0] Q;
  logic [SECTION_WIDTH-1:0] D     = '0;
  logic [6:0]               RA    = '0;
  logic [6:0]               WA    = '0;
  logic RCSN  = 1'b1;

  logic RCSN0 = 1'b1;
  logic RCSN1 = 1'b1;
  logic RCSN2 = 1'b1;
  logic RCSN3 = 1'b1;

  logic WCK;
  logic WCSN  = 1'b1;

  logic WEN   = 1'b1;

  logic [SECTION_WIDTH-1:0] M   = '1;

  logic [7:0]               MCT = '0;

  // End-of-test flag
  logic eot = 1'b0;

  assign WCK = RCK;

  spatz_DIMC #(
    .SECTION_WIDTH (SECTION_WIDTH)
  ) i_dut (
    .RCK     (RCK),
    .RESETn  (RESETn),
    .READYN  (READYN),
    .COMPE   (COMPE),
    .FCSN    (FCSN),
    .MODE    (MODE),
    .FA      (FA),
    .FD      (FD),
    .ADDIN   (ADDIN),
    .SOUT    (SOUT),
    .RES_OUT (RES_OUT),
    .PSOUT   (PSOUT),
    .Q       (Q),
    .D       (D),
    .RA      (RA),
    .WA      (WA),
    .RCSN    (RCSN),
    .RCSN0   (RCSN0),
    .RCSN1   (RCSN1),
    .RCSN2   (RCSN2),
    .RCSN3   (RCSN3),
    .WCK     (WCK),
    .WCSN    (WCSN),
    .WEN     (WEN),
    .M       (M),
    .MCT     (MCT)
  );

  // CLOCK GENERATION AND RESET
  initial begin
    RCK    = 1'b0;
    RESETn = 1'b0;   // assert reset from simulation time 0
    repeat (3) begin
      #(ClkPeriod/2) RCK = 1'b0;
      #(ClkPeriod/2) RCK = 1'b1;
    end
    RESETn = 1'b1;   // release reset; DUT is now operational
    forever begin
      #(ClkPeriod/2) RCK = 1'b0;
      #(ClkPeriod/2) RCK = 1'b1;
    end
  end

  task automatic write_kernel_section(
    input [4:0]               row,   // which of the 32 kernel rows to write
    input [1:0]               sec,   // which 256-bit section within that row (0-3)
    input [SECTION_WIDTH-1:0] data   // the 256-bit data to write
  );
    @(posedge RCK); #ApplTime;
    // Assert write controls; RCSN=1 and FCSN=1 ensure no read or
    // feature-load fires simultaneously.
    COMPE = 1'b0; WA = {row, sec}; D = data; M = '1;
    WCSN = 1'b0; WEN = 1'b0; RCSN = 1'b1; FCSN = 1'b1;

    @(posedge RCK); #ApplTime;   // this posedge latches the write into SRAM
    WCSN = 1'b1; WEN = 1'b1;    // deassert; clear data bus
    D = '0;
  endtask

 task automatic write_full_kernel(
    input [SECTION_WIDTH-1:0] data [0:NB_KERNEL_ROWS*4-1]   // 128 × 256-bit sections
  );
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          @(posedge RCK); #ApplTime;
          COMPE = 1'b0; WA = {5'(r), 2'(s)}; D = data[r*4 + s]; M = '1;
          WCSN = 1'b0; WEN = 1'b0; RCSN = 1'b1; FCSN = 1'b1;
        end
      end

      @(posedge RCK); #ApplTime;   // latches the last entry
      WCSN = 1'b1; WEN = 1'b1;    // deassert; clear data bus
      D = '0;
  endtask
  
  task automatic read_kernel(
    input  [4:0]               row,    // row to read
    input  [1:0]               sec,    // section within that row (0-3)
    output [SECTION_WIDTH-1:0] rdata   // captured output from Q port
  );
    @(posedge RCK); #ApplTime;
    COMPE = 1'b0; RCSN = 1'b0; RA = {row, sec};
    WCSN = 1'b1; WEN = 1'b1; FCSN = 1'b1;   // ensure write and feature paths are idle

    @(posedge RCK); #TestTime;   // Q is registered at this posedge; stable by +TestTime
    rdata = Q;
    RCSN  = 1'b1;   // deassert read enable
  endtask

task automatic load_feature(
    input [SECTION_WIDTH-1:0] f0,   // section 0: bits [255:0]
    input [SECTION_WIDTH-1:0] f1,   // section 1: bits [511:256]
    input [SECTION_WIDTH-1:0] f2,   // section 2: bits [767:512]
    input [SECTION_WIDTH-1:0] f3    // section 3: bits [1023:768]
  );
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd0; FD = f0;  // latch section 0
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd1; FD = f1;  // latch section 1
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd2; FD = f2;  // latch section 2
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd3; FD = f3;  // latch section 3
    @(posedge RCK); #ApplTime; FCSN = 1'b1; FD = '0;              // deassert; buffer retains values
  endtask


  task automatic compute_and_capture(
    input  [4:0]  row,      // kernel row to compute dot product for (0-31)
    input  [23:0] bias,     // 24-bit signed bias added at Stage 3
    input  [7:0]  mct_val,  // MCT value: controls how many elements are active
    output [23:0] psout,    // captured PSOUT (raw psum before ReLU)
    output [3:0]  quant     // captured {RES_OUT, SOUT} (4-bit quantized result)
  );
    // --- Cycle N: assert compute trigger for exactly one cycle ---
    @(posedge RCK); #ApplTime;
    COMPE = 1'b1;                             // trigger the pipeline
    MODE  = 2'b11;                            // 8-bit MAC mode
    MCT   = mct_val;                          // set masking threshold
    RA    = {row, 2'b00};                     // row address; section bits ignored in compute mode
    ADDIN = bias;                             // bias to add at Stage 3
    RCSN  = 1'b0; RCSN0 = 1'b0; RCSN1 = 1'b0; RCSN2 = 1'b0; RCSN3 = 1'b0;  // enable all sections
    WCSN  = 1'b1; WEN   = 1'b1; FCSN  = 1'b1;   // write and feature paths must be idle

    // --- Cycle N+1: deassert trigger; Stage 0 captures inputs ---
    @(posedge RCK); #ApplTime;
    COMPE = 1'b0;
    RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;

    // --- Cycles N+2 and N+3: pipeline progresses through Stages 1 and 2 ---
    @(posedge RCK);   // Stage 1: MCT masking
    @(posedge RCK);   // Stage 2: MAC accumulation

    // --- Cycle N+4: Stage 3 completes; READYN should now be LOW ---
    @(posedge RCK); #TestTime;
    if (READYN !== 1'b0)
      $error("[TB] READYN did not go low after 4-cycle pipeline latency (row=%0d)", row);

    // Capture results while Stage 3 outputs are stable
    psout = PSOUT;
    quant = {RES_OUT, SOUT};    // reassemble 4-bit result from its two output ports
  endtask

  
  task automatic compute_all_rows_pipelined(
    input  [23:0] bias,
    input  [7:0]  mct_val,
    output [23:0] psout_out [0:NB_KERNEL_ROWS-1],
    output [3:0]  quant_out [0:NB_KERNEL_ROWS-1]
  );
    for (int i = 0; i < NB_KERNEL_ROWS + 4; i++) begin
      @(posedge RCK); #ApplTime;

      if (i < NB_KERNEL_ROWS) begin
        COMPE = 1'b1;
        MODE  = 2'b11;
        MCT   = mct_val;
        RA    = {5'(i), 2'b00};
        ADDIN = bias;
        RCSN  = 1'b0; RCSN0 = 1'b0; RCSN1 = 1'b0; RCSN2 = 1'b0; RCSN3 = 1'b0;
        WCSN  = 1'b1; WEN   = 1'b1; FCSN  = 1'b1;
      end else begin
        COMPE = 1'b0;
        RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
      end

      // when i = ? -- exactly 5 pos edges already happened since the request was made 
      // as per the test bench, posedge happends and then 
      if (i >= 5) begin
        #(TestTime - ApplTime);
        if (READYN !== 1'b0)
          $error("[TB] READYN not low at pipelined result cycle for row %0d", i - 5);
        psout_out[i - 5] = PSOUT;
        quant_out[i - 5] = {RES_OUT, SOUT};
      end
    end

    @(posedge RCK); #ApplTime;
    COMPE = 1'b0;
    RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
  endtask

 
  // PASS / FAIL COUNTERS
  int pass_count = 0;
  int fail_count = 0;

  // =========================================================================
  // MAIN TEST SEQUENCE
  // =========================================================================
  initial begin
    // Local variables used across multiple tests
    logic [SECTION_WIDTH-1:0] rd_data;                 // captured kernel readback data
    logic [23:0]              psout, psout_expected;   // psum from DUT and golden
    logic [3:0]               quant, quant_expected;   // 4-bit result from DUT and golden
    logic [23:0]              psout_pipe [0:NB_KERNEL_ROWS-1];  // per-row psum captured by Test 6
    logic [3:0]               quant_pipe [0:NB_KERNEL_ROWS-1]; // per-row quant captured by Test 6

    // Wait for reset to release (driven by the clock initial block)
    @(posedge RESETn);
    // One extra idle cycle so all DUT output registers settle cleanly from reset
    @(posedge RCK);

    
    $readmemh(KERNEL_WEIGHTS_FILE,        kernel_stim);    // 128 entries: 32 rows × 4 sections
    $readmemh(FEATURE_VECTOR_FILE,        feature_stim);   //   4 entries: one per 256-bit section
    $readmemh(GOLDEN_MATVEC_FILE,          golden_4bit);  //  32 entries: expected 4-bit result per row
    $readmemh(GOLDEN_PSOUT_FILE,           golden_psout);   //  32 entries: expected 24-bit psum per row
    $readmemh(GOLDEN_DOT_PRODUCT_MCT_FILE, golden_mct);     //   6 entries: 4-bit result for row 0 per MCT
    $readmemh(GOLDEN_PSOUT_MCT_FILE,       golden_psout_mct); // 6 entries: 24-bit psum for row 0 per MCT

`ifdef TB_DIMC_TEST5
    // =======================================================================
    // TEST 5: RESET VERIFICATION
    // =======================================================================
    // After RESETn releases, the DUT should hold every output and every
    // internal memory location at zero (except READYN which should be 1,
    // meaning "not ready", since no compute has been triggered).
    //
    // Checks performed:
    //   READYN == 1   (no spurious ready signal)
    //   PSOUT  == 0   (psum register cleared)
    //   {RES_OUT, SOUT} == 0  (quantized output cleared)
    //   Q == 0        (memory read output cleared)
    //   feature_buf[0..3] == 0  (feature buffer cleared, via hierarchical ref)
    //   kernel_mem[0..31][0..3] == 0  (SRAM cleared, via hierarchical ref)
    //
    // Hierarchical references (i_dut.feature_buf, i_dut.kernel_mem) are used
    // because these internal memories have no dedicated read port for direct
    // external access — the only way to see them from the testbench is to
    // look directly inside the DUT's hierarchy.
    // =======================================================================
    $display("[TB] Test 5: Reset verification");
    @(posedge RCK); #TestTime;

    begin
      automatic logic reset_ok = 1'b1;
      if (READYN !== 1'b1)         reset_ok = 1'b0;   // must be NOT-ready
      if (PSOUT  !== 24'h0)        reset_ok = 1'b0;   // psum cleared
      if ({RES_OUT,SOUT} !== 4'h0) reset_ok = 1'b0;   // quant output cleared
      if (Q !== '0)                reset_ok = 1'b0;   // memory read port cleared
      // Check feature buffer via hierarchical reference (no external read port)
      for (int s = 0; s < 4; s++)
        if (i_dut.feature_buf[s] !== '0) reset_ok = 1'b0;
      // Check kernel SRAM via hierarchical reference (32 rows × 4 sections)
      for (int r = 0; r < NB_KERNEL_ROWS; r++)
        for (int s = 0; s < 4; s++)
          if (i_dut.kernel_mem[r][s] !== '0) reset_ok = 1'b0;
      if (!reset_ok) begin $error("[TB] Test5 FAIL: one or more signals not zero/one after reset"); fail_count++; end
      else           begin $display("[TB] Test 5: PASS"); pass_count++; end
    end
`endif // TB_DIMC_TEST5



`ifdef TB_DIMC_TEST1
    // =======================================================================
    // TEST 1: KERNEL WRITE + READ-BACK
    // =======================================================================
    // Writes every section of every kernel row using write_kernel_section, then
    // immediately reads it back with read_kernel and compares Q against
    // what was written.  This verifies the SRAM's read and write paths
    // independently of the compute pipeline.
    //
    // 32 rows × 4 sections = 128 write+readback pairs.
    // A single failure counter tracks all mismatches; the test passes only
    // if every readback exactly matches what was written.
    // =======================================================================
    $display("[TB] Test 1: Kernel write + read-back");
    begin
      automatic int test_fail = 0;
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          write_kernel_section(5'(r), 2'(s), kernel_stim[r*4 + s]);   // write one section
          read_kernel(5'(r), 2'(s), rd_data);                  // read it back
          if (rd_data !== kernel_stim[r*4 + s]) begin
            $error("[TB] Test1 row%0d sec%0d: got 0x%h, expected 0x%h",
                   r, s, rd_data, kernel_stim[r*4 + s]);
            test_fail++;
          end
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 1: PASS"); pass_count++; end
      else                begin $display("[TB] Test 1: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // TB_DIMC_TEST1

`ifdef TB_DIMC_TEST1B
// =======================================================================
    // TEST 1B: efficient version of KERNEL WRITE + READ-BACK
    // =======================================================================
    // this version needs only 129 cycles instead of 256 cycles for the previous version
    // =======================================================================
    $display("[TB] Test 1B: optimized Kernel write + read-back");
    begin
      automatic int     test_fail = 0;
      automatic longint t_start, t_end;
      @(posedge RCK); t_start = $time;   // align to posedge so division is exact
      write_full_kernel(kernel_stim);
      t_end = $time;
      $display("[TB] Test 1B: write_full_kernel took %0d cycles", (t_end - t_start + ClkPeriod/2) / ClkPeriod);
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          read_kernel(5'(r), 2'(s), rd_data);                  // read it back
          if (rd_data !== kernel_stim[r*4 + s]) begin
            $error("[TB] Test1B row%0d sec%0d: got 0x%h, expected 0x%h",
                   r, s, rd_data, kernel_stim[r*4 + s]);
            test_fail++;
          end
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 1B optimized: PASS"); pass_count++; end
      else                begin $display("[TB] Test 1B optimized: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // TB_DIMC_TEST1B

`ifdef TB_DIMC_TEST2
    // =======================================================================
    // TEST 2: LOAD FEATURE VECTOR
    // =======================================================================
    // Writes the 4 × 256-bit feature vector sections into the DUT's internal
    // feature buffer.  There is no external read port on the feature buffer,
    // so this test cannot verify correctness directly.  Correct loading is
    // confirmed indirectly by the compute results in Test 3.
    //
    // After this task returns, the DUT's feature_buf holds the complete
    // 1024-bit feature vector that will be used for all subsequent MACs.
    // =======================================================================
    $display("[TB] Test 2: Load feature vector");
    load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);
`endif // TB_DIMC_TEST2

`ifdef TB_DIMC_TEST3
    // =======================================================================
    // TEST 3: FULL MATRIX-VECTOR MULTIPLICATION (32 rows, MCT=0)
    // =======================================================================
    // Exercises the full MAC pipeline for every kernel row.
    //
    //   Computes for each row r:
    //     psum[r]  = dot(kernel[r], feature, MCT=0) + BIAS   (24-bit, all 128 elements active)
    //     quant[r] = ReLU4(psum[r])                           (4-bit clipped result)
    //
    // Both outputs must match the golden files produced by gen_stim.py:
    //   golden_psout[r]  — 24-bit psum before ReLU (from golden_psout.txt)
    //   golden_4bit[r] — 4-bit quantized result (from golden_4bit.txt)
    //
    // MCT=0 means no masking: all 128 byte-elements of every row participate.
    // The kernel and feature are already loaded by Tests 1 and 2.
    // =======================================================================
    $display("[TB] Test 3: Full matrix-vector multiplication (32 rows)");
    begin
      automatic int test_fail = 0;
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        compute_and_capture(5'(r), BIAS, 8'd0, psout, quant);
        // Check both the raw psum and the quantized output independently
        if (psout !== golden_psout[r] || quant !== golden_4bit[r][3:0]) begin
          if (psout !== golden_psout[r])
            $error("[TB] Test3 row%0d: psout got 0x%06h, expected 0x%06h", r, psout, golden_psout[r]);
          if (quant !== golden_4bit[r][3:0])
            $error("[TB] Test3 row%0d: quant got %0d, expected %0d", r, quant, golden_4bit[r][3:0]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 3: PASS"); pass_count++; end
      else                begin $display("[TB] Test 3: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // TB_DIMC_TEST3

`ifdef TB_DIMC_TEST4
    // =======================================================================
    // TEST 4: MCT MASKING SWEEP
    // =======================================================================
    // Verifies that the MCT masking hardware correctly trims the number of
    // active byte-elements in the dot product for row 0.
    //
    // Row 0 is computed once for each of the 6 MCT values in MCT_VALS:
    //   MCT=  0 → 128 active elements (full row, no masking)
    //   MCT=128 →  64 active elements (lower half of the row)
    //   MCT=192 →  32 active elements (first section only)
    //   MCT=224 →  16 active elements
    //   MCT=240 →   8 active elements
    //   MCT=248 →   4 active elements (almost fully masked)
    //
    // Expected results come from golden_dot_product_mct.txt (4-bit quant)
    // and golden_psout_mct.txt (24-bit psum before ReLU), both generated
    // by gen_stim.py using the same MCT masking logic as the DUT.
    //
    // The kernel and feature are still in the DUT from Tests 1 and 2.
    // =======================================================================
    $display("[TB] Test 4: MCT masking sweep (%0d values, row 0)", NB_MCT_VALS);
    begin
      automatic logic [23:0] psout;
      automatic logic [3:0]  quant;

      automatic int test_fail = 0;
      for (int m = 0; m < NB_MCT_VALS; m++) begin
        compute_and_capture(5'd0, BIAS, MCT_VALS[m], psout, quant);
        if (psout !== golden_psout_mct[m] || quant !== golden_mct[m][3:0]) begin
          if (psout !== golden_psout_mct[m])
            $error("[TB] Test4 MCT=0x%02h row0: psout got 0x%06h, expected 0x%06h",
                   MCT_VALS[m], psout, golden_psout_mct[m]);
          if (quant !== golden_mct[m][3:0])
            $error("[TB] Test4 MCT=0x%02h row0: quant got %0d, expected %0d",
                   MCT_VALS[m], quant, golden_mct[m][3:0]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 4: PASS"); pass_count++; end
      else                begin $display("[TB] Test 4: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // TB_DIMC_TEST4

    
    // FINAL SUMMARY
    $display("[TB] ================================================");
    $display("[TB] RESULTS: %0d PASSED, %0d FAILED", pass_count, fail_count);
    $display("[TB] ================================================");
    if (fail_count == 0) $display("[TB] ALL TESTS PASSED");
    else                  $display("[TB] FAILURES DETECTED");
    $display("Testbench: Test finished.");
    eot = 1'b1;   // signal completion to any external watcher
    $finish;
  end

  // WAVEFORM DUMP
  initial begin
    $dumpfile("sim/tb_DIMC.vcd");
    $dumpvars(0, tb_DIMC);
  end

  
  /** WATCHDOG TIMER **/
  // Kills the simulation after 50 µs (5000 clock cycles at 100 MHz).
  // trip always indicates a bug.
  initial begin
    #(5000 * ClkPeriod);
    $error("[TB] WATCHDOG: simulation exceeded 50 us");
    $finish;
  end

endmodule
