/*
 * tb_DIMC_18_fixed.sv
 *
 * ============================================================
 * PURPOSE
 * ============================================================
 * Testbench for the DIMC_18_fixed module (defined in spatz_DIMC.sv).
 *
 * DIMC_18_fixed is a Digital In-Memory Computing (DIMC) accelerator
 * that performs matrix–vector multiplication (MatVec) in hardware:
 *
 *   y[r] = ReLU4( dot(kernel[r], feature) + bias )    for r = 0..31
 *
 * where:
 *   - kernel[r] is a 128-element row of uint8 weights stored in an
 *     on-chip SRAM (32 rows × 128 bytes = 32 × 1024 bits).
 *   - feature is a 128-element uint8 input vector loaded into a
 *     feature buffer inside the DUT.
 *   - bias (ADDIN) is a 24-bit signed constant added to the raw
 *     MAC result before quantization.
 *   - ReLU4 clamps negatives to 0 and values > 15 to 15, producing
 *     a 4-bit output per row.
 *
 * ============================================================
 * MEMORY ORGANISATION
 * ============================================================
 * The 1024-bit kernel row and feature vector are each split into
 * four 256-bit sections (SECTION_WIDTH = 256).  Addresses encode
 * both the row and section:
 *
 *   WA / RA [6:2] = row index (0-31)
 *   WA / RA [1:0] = section index (0-3)
 *
 * The feature buffer is written section-by-section too:
 *   FA [1:0] = section index (0-3), FD = 256-bit section data
 *
 * ============================================================
 * PIPELINE LATENCY
 * ============================================================
 * The DUT computes in four pipelined stages after compute is
 * triggered at posedge P(N) + ApplTime:
 *
 *   P(N+1) — Stage 0: input capture: latches kernel row, feature,
 *                      MCT, and ADDIN into pipeline registers
 *   P(N+2) — Stage 1: MCT masking applied to byte-elements
 *   P(N+3) — Stage 2: MAC (multiply-accumulate) over all 128 bytes
 *   P(N+4) — Stage 3: psum = MAC + ADDIN; ReLU + 4-bit quantisation;
 *                      READYN goes low to signal valid output
 *
 * Outputs (PSOUT, READYN, SOUT, RES_OUT) are sampled at
 * P(N+4) + TestTime to allow combinational logic to settle.
 *
 * ============================================================
 * MCT MASKING
 * ============================================================
 * The MCT (Mask Count Threshold) port trims the active portion of
 * each kernel row:
 *
 *   valid_bits = 1024 − MCT × 4
 *   element i (8-bit) is active when i×8 < valid_bits
 *
 * MCT = 0   → all 128 elements active (no masking, full dot product)
 * MCT = 128 → only 64 elements active (lower half of the row)
 * MCT = 192 → only 32 elements active (first section only)
 * … and so on.  This is tested in Test 4.
 *
 * ============================================================
 * TEST STRUCTURE
 * ============================================================
 * All stimulus (kernel weights, feature vector) and golden outputs
 * are generated by gen_stim.py before simulation.  The testbench
 * reads them at runtime with $readmemh.
 *
 * Test 5 — Reset: verify all DUT outputs and memories are zero
 * Test 1 — Kernel write + readback: 32 rows × 4 sections
 * Test 2 — Feature load: 4 × 256-bit sections into feature buffer
 * Test 3 — Full MatVec: all 32 rows, MCT=0, check psout + quant
 * Test 4 — MCT sweep: row 0 at 6 different MCT values
 *
 * ============================================================
 * QUICK-START
 * ============================================================
 *   cd hw/ip/spatz/tb
 *   python3 gen_stim.py --seed 14
 *   module load questasim
 *   vlib work
 *   vlog -sv ../src/spatz_DIMC.sv tb_DIMC_18_fixed.sv
 *   vsim -c tb_DIMC_18_fixed -do "run -all; quit"
 */

`timescale 1ns/1ps

module tb_DIMC_18_fixed;

  // -------------------------------------------------------------------------
  // Parameters
  // -------------------------------------------------------------------------
  // SECTION_WIDTH: each of the four memory sections is 256 bits wide.
  //   Four sections × 256 bits = 1024 bits = one full kernel row or
  //   one full feature vector.
  parameter SECTION_WIDTH  = 256;

  // NB_KERNEL_ROWS: the DUT stores 32 rows of kernel weights.
  //   Each row is 128 uint8 elements = 1024 bits = 4 × 256-bit sections.
  parameter NB_KERNEL_ROWS = 32;

  // Stimulus files produced by gen_stim.py.
  // They must be present in the simulator's working directory before
  // the simulation runs; gen_stim.py writes them to the current directory.
  parameter KERNEL_WEIGHTS_FILE        = "kernel_weights.txt";       // File 1
  parameter FEATURE_VECTOR_FILE        = "feature_vector.txt";       // File 2
  parameter GOLDEN_MATVEC_FILE          = "golden_matvec.txt";       // File 3
  parameter GOLDEN_PSOUT_FILE           = "golden_psout.txt";        // File 4
  parameter GOLDEN_DOT_PRODUCT_MCT_FILE = "golden_dot_product_mct.txt"; // File 5
  parameter GOLDEN_PSOUT_MCT_FILE       = "golden_psout_mct.txt";    // File 6

  // NB_MCT_VALS: how many distinct MCT values are swept in Test 4.
  // Must equal len(MCT_VALS) in gen_stim.py.
  parameter NB_MCT_VALS = 6;

  // BIAS: constant 24-bit signed value added to every MAC result at Stage 3.
  // The large negative value centres the raw psum (≈ 2,080,000 for random
  // uint8 data: 128 elements × E[k×f] ≈ 127.5²) near 8, the midpoint of
  // the [0, 15] quantisation range.
  // MUST match the BIAS constant in gen_stim.py.
  localparam logic signed [23:0] BIAS = -2_080_000;

  // MCT_VALS: the six threshold values swept in Test 4.
  // Each value trims a different number of byte-elements from the computation.
  // MUST match MCT_VALS in gen_stim.py.
  localparam logic [7:0] MCT_VALS [NB_MCT_VALS] = '{8'd0, 8'd128, 8'd192, 8'd224, 8'd240, 8'd248};

  // -------------------------------------------------------------------------
  // Stimulus and golden arrays
  // These are filled by $readmemh at the start of the test sequence.
  // -------------------------------------------------------------------------
  // kernel_stim: flattened kernel SRAM contents.
  //   Index = row*4 + section → 32 rows × 4 sections = 128 entries total.
  //   Each entry is one 256-bit section of one kernel row.
  logic [SECTION_WIDTH-1:0] kernel_stim  [0 : NB_KERNEL_ROWS*4-1];

  // feature_stim: the 1024-bit feature vector split into 4 × 256-bit sections.
  //   feature_stim[0] = bits [255:0], feature_stim[3] = bits [1023:768].
  logic [SECTION_WIDTH-1:0] feature_stim [0 : 3];

  // golden_matvec: expected 4-bit quantized output per row after ReLU+quant.
  //   Computed as ReLU4( dot(kernel[r], feature, MCT=0) + BIAS ).
  //   Stored in the lower nibble of each byte (upper nibble is 0).
  logic [7:0]  golden_matvec  [0 : NB_KERNEL_ROWS-1];

  // golden_psout: expected 24-bit partial sum per row BEFORE ReLU+quant.
  //   = ( dot(kernel[r], feature, MCT=0) + BIAS ) masked to 24 bits.
  //   This is the raw pipeline output before clamping; used to debug
  //   whether errors are in the accumulator or in the quantizer.
  logic [23:0] golden_psout   [0 : NB_KERNEL_ROWS-1];

  // golden_mct: expected 4-bit result for row 0 at each MCT value.
  //   Entry m corresponds to MCT_VALS[m].
  logic [7:0]  golden_mct     [0 : NB_MCT_VALS-1];

  // golden_psout_mct: expected 24-bit psum for row 0 at each MCT value,
  //   BEFORE ReLU+quant.  One entry per MCT_VALS element.
  logic [23:0] golden_psout_mct[0 : NB_MCT_VALS-1];

  // -------------------------------------------------------------------------
  // Timing parameters
  // -------------------------------------------------------------------------
  // ClkPeriod: 10 ns = 100 MHz system clock.
  localparam time ClkPeriod = 10ns;

  // ApplTime: signals are driven ApplTime after the rising edge.
  //   This models realistic signal propagation and ensures that the DUT
  //   sees stable inputs well before the next rising edge (setup = 8 ns).
  localparam time ApplTime  =  2ns;

  // TestTime: outputs are sampled TestTime after the rising edge.
  //   Chosen so that all combinational paths in Stage 3 have settled by
  //   the time we read PSOUT, SOUT, and RES_OUT.
  localparam time TestTime  =  8ns;

  // NUM_SECTIONS: how many 256-bit sections make up one kernel row or
  //   feature vector (= 1024 / 256 = 4).
  localparam NUM_SECTIONS = 1024 / SECTION_WIDTH;

  // ROW_WIDTH: total width of one kernel row or feature vector in bits.
  localparam ROW_WIDTH    = 1024;

  // =========================================================================
  // DUT SIGNAL DECLARATIONS
  // =========================================================================
  // Signals are grouped by function.  Active-low signals end in N (READYN,
  // FCSN, RCSN, WCSN, WEN, RESETn) — they are logically asserted when low.

  // -------------------------------------------------------------------------
  // Clocks and reset
  // -------------------------------------------------------------------------
  // RCK: the only clock the DUT uses.  WCK (write clock) is tied to RCK.
  logic RCK;
  // RESETn: synchronous active-low reset.  While low the DUT holds all
  // registers at zero (outputs = 0, memories = 0, READYN = 1).
  logic RESETn;

  // -------------------------------------------------------------------------
  // Status and mode
  // -------------------------------------------------------------------------
  // READYN (DUT output): goes LOW when Stage 3 of the pipeline holds a valid
  //   result.  The testbench samples PSOUT / SOUT / RES_OUT only when READYN=0.
  //   No initial value — driven entirely by the DUT.
  logic        READYN;

  // COMPE: assert HIGH for exactly one clock cycle to launch a compute
  //   operation.  When high, the DUT captures RA[6:2] (row index), MCT,
  //   ADDIN and the stored feature vector, and begins the 4-stage pipeline.
  logic        COMPE  = 1'b0;

  // FCSN: Feature Chip-Select (active-LOW).  While low, the DUT writes
  //   FD into feature_buf[FA] on the next rising edge.
  //   Initialised to 1 so the feature buffer is NOT written at time 0.
  logic        FCSN   = 1'b1;

  // MODE: 2-bit operation mode.  2'b11 selects full 8-bit MAC mode.
  //   This testbench always uses 8-bit mode; other modes are not tested here.
  logic [1:0]  MODE   = 2'b11;

  // -------------------------------------------------------------------------
  // Feature buffer write port
  // -------------------------------------------------------------------------
  // FA: 2-bit Feature Address — selects which 256-bit section of the
  //   feature buffer (0-3) is written when FCSN = 0.
  logic [1:0]               FA    = '0;

  // FD: Feature Data — 256-bit section to load into the feature buffer.
  //   Initialised to 0 so the bus is not floating before load_feature is called.
  logic [SECTION_WIDTH-1:0] FD    = '0;

  // -------------------------------------------------------------------------
  // Compute bias
  // -------------------------------------------------------------------------
  // ADDIN: 24-bit signed value added to the MAC accumulator result at Stage 3.
  //   Used as a bias term: psum = MAC_result + ADDIN.
  //   0 by default; tasks that need a bias set this before triggering compute.
  logic [23:0]              ADDIN = '0;

  // -------------------------------------------------------------------------
  // Compute outputs (driven by DUT)
  // -------------------------------------------------------------------------
  // SOUT: MSB (bit 3) of the 4-bit quantized output.  Combined with RES_OUT
  //   to form the full result: {RES_OUT[2:0], SOUT} = 4-bit quant value.
  logic                     SOUT;

  // RES_OUT: lower 3 bits [2:0] of the 4-bit quantized output.
  logic [2:0]               RES_OUT;

  // PSOUT: 24-bit partial sum BEFORE ReLU+quantization.
  //   = MAC_accumulator + ADDIN, stored in a 24-bit register at Stage 3.
  //   Useful for debugging: if PSOUT is correct but quant is wrong, the
  //   error is in the ReLU/quantization stage.
  logic [23:0]              PSOUT;

  // Q: 256-bit memory read output.  Valid one cycle after a read is triggered
  //   (RCSN=0, COMPE=0).  Reflects kernel_mem[RA[6:2]][RA[1:0]].
  logic [SECTION_WIDTH-1:0] Q;

  // -------------------------------------------------------------------------
  // Kernel SRAM write port
  // -------------------------------------------------------------------------
  // D: 256-bit data bus for writing one section into the kernel SRAM.
  //   Initialised to 0 so no garbage is written if WCSN/WEN glitch.
  logic [SECTION_WIDTH-1:0] D     = '0;

  // RA: 7-bit read address.
  //   RA[6:2] = row (0-31)   — which of the 32 kernel rows to read/compute
  //   RA[1:0] = section (0-3) — which 256-bit section within that row
  //   In COMPUTE mode (COMPE=1), only RA[6:2] matters; section bits are
  //   ignored because the DUT reads all four sections automatically.
  logic [6:0]               RA    = '0;

  // WA: 7-bit write address — same bit encoding as RA but for SRAM writes.
  logic [6:0]               WA    = '0;

  // -------------------------------------------------------------------------
  // Memory chip-selects (all active-LOW; start deasserted = 1)
  // -------------------------------------------------------------------------
  // RCSN: Global read chip-select.
  //   In read mode (COMPE=0, RCSN=0): enables reading kernel_mem[RA] → Q.
  //   In compute mode (COMPE=1): must also be 0 to enable the MAC datapath.
  logic RCSN  = 1'b1;

  // RCSN0-3: Per-section read enables.  ALL four must be simultaneously
  //   asserted (=0) together with RCSN and COMPE=1 to trigger a full-row MAC.
  //   This ensures that all four 256-bit sections participate in the computation.
  logic RCSN0 = 1'b1;
  logic RCSN1 = 1'b1;
  logic RCSN2 = 1'b1;
  logic RCSN3 = 1'b1;

  // WCK: write clock, tied directly to RCK (the DUT uses a single clock domain).
  logic WCK;

  // WCSN: Write Chip-Select (active-LOW).  Combined with WEN to gate writes.
  //   mem_write_en = ~COMPE & ~WCSN & ~WEN inside the DUT.
  logic WCSN  = 1'b1;

  // WEN: Write Enable (active-LOW).  Both WCSN and WEN must be low to write.
  logic WEN   = 1'b1;

  // -------------------------------------------------------------------------
  // Write masking
  // -------------------------------------------------------------------------
  // M: 256-bit write mask.  A 1 in position i means bit i of D is written
  //   through to the SRAM.  '1 (all ones) means write the full word.
  logic [SECTION_WIDTH-1:0] M   = '1;

  // MCT: 8-bit Mask Count Threshold — trims the active elements of each MAC.
  //   valid_bits = 1024 - MCT*4.  Element i is active when i*8 < valid_bits.
  //   0 = full row (128 elements), higher values mask out trailing elements.
  logic [7:0]               MCT = '0;

  // -------------------------------------------------------------------------
  // End-of-test flag
  // -------------------------------------------------------------------------
  // Asserted at the very end of the test sequence, useful for waveform viewers
  // and any external monitoring scripts to detect simulation completion.
  logic eot = 1'b0;

  // =========================================================================
  // DUT INSTANTIATION
  // =========================================================================
  // The write clock is identical to the read clock — the DUT is fully
  // synchronous on a single clock domain.  (spatz_DIMC.sv line 99 shows
  // WCK entering the same clock network as RCK.)
  assign WCK = RCK;

  DIMC_18_fixed #(
    .SECTION_WIDTH (SECTION_WIDTH)
  ) i_dut (
    .RCK     (RCK),
    .RESETn  (RESETn),
    .READYN  (READYN),
    .COMPE   (COMPE),
    .FCSN    (FCSN),
    .MODE    (MODE),
    .FA      (FA),
    .FD      (FD),
    .ADDIN   (ADDIN),
    .SOUT    (SOUT),
    .RES_OUT (RES_OUT),
    .PSOUT   (PSOUT),
    .Q       (Q),
    .D       (D),
    .RA      (RA),
    .WA      (WA),
    .RCSN    (RCSN),
    .RCSN0   (RCSN0),
    .RCSN1   (RCSN1),
    .RCSN2   (RCSN2),
    .RCSN3   (RCSN3),
    .WCK     (WCK),
    .WCSN    (WCSN),
    .WEN     (WEN),
    .M       (M),
    .MCT     (MCT)
  );

  // =========================================================================
  // CLOCK GENERATION AND RESET
  // =========================================================================
  // The clock block runs first at time 0:
  //   - RCK starts LOW, RESETn starts asserted (LOW = in reset).
  //   - Three full clock cycles pass while reset is held (30 ns).
  //     This ensures the DUT has multiple cycles to clear all registers.
  //   - RESETn releases to HIGH; the DUT becomes operational.
  //   - The clock continues toggling forever for the remainder of the sim.
  initial begin
    RCK    = 1'b0;
    RESETn = 1'b0;   // assert reset from simulation time 0
    repeat (3) begin
      #(ClkPeriod/2) RCK = 1'b0;
      #(ClkPeriod/2) RCK = 1'b1;
    end
    RESETn = 1'b1;   // release reset; DUT is now operational
    forever begin
      #(ClkPeriod/2) RCK = 1'b0;
      #(ClkPeriod/2) RCK = 1'b1;
    end
  end

  // =========================================================================
  // PROTOCOL TASKS
  // =========================================================================
  // These tasks encapsulate the signal sequences needed to exercise the DUT.
  // Each one waits for clock edges and drives signals with ApplTime delay
  // so the DUT sees stable values well before the next rising edge.

  // ---------------------------------------------------------------------------
  // write_kernel — drives one 256-bit section into the kernel SRAM.
  //
  // HOW IT WORKS (two clock cycles):
  //
  //   Cycle A (apply):  Assert WCSN=0 and WEN=0 at ApplTime after posedge.
  //                     Inside the DUT, mem_write_en = ~COMPE & ~WCSN & ~WEN
  //                     goes HIGH.  Data (D) and address (WA) are stable.
  //
  //   Cycle B (latch):  The next rising edge registers the write:
  //                     kernel_mem[WA[6:2]][WA[1:0]] <= D
  //                     After ApplTime, WCSN and WEN are deasserted so that
  //                     no second write fires on the following edge.
  //
  // ADDRESS ENCODING:
  //   WA[6:2] = row index (5-bit, 0-31)
  //   WA[1:0] = section index (2-bit, 0-3)
  //   Combined: {row[4:0], sec[1:0]} = 7 bits → WA
  // ---------------------------------------------------------------------------
  task automatic write_kernel(
    input [4:0]               row,   // which of the 32 kernel rows to write
    input [1:0]               sec,   // which 256-bit section within that row (0-3)
    input [SECTION_WIDTH-1:0] data   // the 256-bit data to write
  );
    @(posedge RCK); #ApplTime;
    // Assert write controls; RCSN=1 and FCSN=1 ensure no read or
    // feature-load fires simultaneously.
    COMPE = 1'b0; WA = {row, sec}; D = data; M = '1;
    WCSN = 1'b0; WEN = 1'b0; RCSN = 1'b1; FCSN = 1'b1;

    @(posedge RCK); #ApplTime;   // this posedge latches the write into SRAM
    WCSN = 1'b1; WEN = 1'b1;    // deassert; clear data bus
    D = '0;
  endtask

  // ---------------------------------------------------------------------------
  // read_kernel — reads one 256-bit section from the kernel SRAM.
  //
  // HOW IT WORKS (one cycle latency):
  //
  //   Cycle A (apply):  Assert RCSN=0 with COMPE=0 and the desired address.
  //                     Inside the DUT, mem_read_en = ~COMPE & ~RCSN goes HIGH.
  //
  //   Cycle B posedge:  The DUT registers Q <= kernel_mem[RA[6:2]][RA[1:0]].
  //                     After TestTime from this posedge, Q is fully stable
  //                     and the task captures it into rdata.
  //
  // COMPE must be LOW during a read; if COMPE were HIGH, the DUT would
  // interpret the operation as a compute trigger rather than a memory read.
  // ---------------------------------------------------------------------------
  task automatic read_kernel(
    input  [4:0]               row,    // row to read
    input  [1:0]               sec,    // section within that row (0-3)
    output [SECTION_WIDTH-1:0] rdata   // captured output from Q port
  );
    @(posedge RCK); #ApplTime;
    COMPE = 1'b0; RCSN = 1'b0; RA = {row, sec};
    WCSN = 1'b1; WEN = 1'b1; FCSN = 1'b1;   // ensure write and feature paths are idle

    @(posedge RCK); #TestTime;   // Q is registered at this posedge; stable by +TestTime
    rdata = Q;
    RCSN  = 1'b1;   // deassert read enable
  endtask

  // ---------------------------------------------------------------------------
  // load_feature — writes all four 256-bit sections into the DUT's feature buffer.
  //
  // HOW IT WORKS:
  //   The DUT has an internal 4-entry × 256-bit feature buffer.  When FCSN=0
  //   on a rising edge, the DUT registers: feature_buf[FA] <= FD.
  //
  //   This task asserts FCSN for four consecutive cycles with FA stepping
  //   0→1→2→3 and FD holding the corresponding section.  A fifth cycle
  //   deasserts FCSN.  After this task returns, feature_buf holds the
  //   complete 1024-bit feature vector, ready for the next compute.
  //
  //   THERE IS NO READ PORT on feature_buf.  Its contents can only be
  //   verified indirectly through a compute operation (Test 3).
  // ---------------------------------------------------------------------------
  task automatic load_feature(
    input [SECTION_WIDTH-1:0] f0,   // section 0: bits [255:0]
    input [SECTION_WIDTH-1:0] f1,   // section 1: bits [511:256]
    input [SECTION_WIDTH-1:0] f2,   // section 2: bits [767:512]
    input [SECTION_WIDTH-1:0] f3    // section 3: bits [1023:768]
  );
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd0; FD = f0;  // latch section 0
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd1; FD = f1;  // latch section 1
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd2; FD = f2;  // latch section 2
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd3; FD = f3;  // latch section 3
    @(posedge RCK); #ApplTime; FCSN = 1'b1; FD = '0;              // deassert; buffer retains values
  endtask

  // ---------------------------------------------------------------------------
  // compute_and_capture — triggers one MAC computation and captures the Stage 3 result.
  //
  // WHAT IT COMPUTES:
  //   Using the kernel row currently stored at address RA[6:2] in the DUT's
  //   SRAM and the feature vector currently in the feature buffer:
  //     psum  = dot_masked(kernel[row], feature, mct_val) + bias
  //     quant = ReLU4(psum)   [4-bit: 0 if negative, 15 if > 15, else psum]
  //
  // TRIGGER PROTOCOL:
  //   1. Assert COMPE=1, all RCSN*=0, and set RA[6:2]=row, MCT=mct_val,
  //      ADDIN=bias for exactly ONE clock cycle.
  //   2. Deassert COMPE and RCSN* on the immediately following cycle.
  //      The pipeline now carries the computation forward without needing
  //      any further inputs.
  //   3. Wait 3 more rising edges (Stages 1, 2, 3 complete).
  //   4. Sample PSOUT, SOUT, RES_OUT at +TestTime after the 4th posedge.
  //
  // NOTE on RA section bits:
  //   In compute mode, only RA[6:2] (the row index) matters.  RA[1:0]
  //   is set to 00 but the DUT reads all four sections automatically.
  //
  // OUTPUTS:
  //   psout — 24-bit PSOUT register value (before ReLU+quant)
  //   quant — 4-bit {RES_OUT[2:0], SOUT} quantized result (after ReLU+quant)
  // ---------------------------------------------------------------------------
  task automatic compute_and_capture(
    input  [4:0]  row,      // kernel row to compute dot product for (0-31)
    input  [23:0] bias,     // 24-bit signed bias added at Stage 3
    input  [7:0]  mct_val,  // MCT value: controls how many elements are active
    output [23:0] psout,    // captured PSOUT (raw psum before ReLU)
    output [3:0]  quant     // captured {RES_OUT, SOUT} (4-bit quantized result)
  );
    // --- Cycle N: assert compute trigger for exactly one cycle ---
    @(posedge RCK); #ApplTime;
    COMPE = 1'b1;                             // trigger the pipeline
    MODE  = 2'b11;                            // 8-bit MAC mode
    MCT   = mct_val;                          // set masking threshold
    RA    = {row, 2'b00};                     // row address; section bits ignored in compute mode
    ADDIN = bias;                             // bias to add at Stage 3
    RCSN  = 1'b0; RCSN0 = 1'b0; RCSN1 = 1'b0; RCSN2 = 1'b0; RCSN3 = 1'b0;  // enable all sections
    WCSN  = 1'b1; WEN   = 1'b1; FCSN  = 1'b1;   // write and feature paths must be idle

    // --- Cycle N+1: deassert trigger; Stage 0 captures inputs ---
    @(posedge RCK); #ApplTime;
    COMPE = 1'b0;
    RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;

    // --- Cycles N+2 and N+3: pipeline progresses through Stages 1 and 2 ---
    @(posedge RCK);   // Stage 1: MCT masking
    @(posedge RCK);   // Stage 2: MAC accumulation

    // --- Cycle N+4: Stage 3 completes; READYN should now be LOW ---
    @(posedge RCK); #TestTime;
    if (READYN !== 1'b0)
      $error("[TB] READYN did not go low after 4-cycle pipeline latency (row=%0d)", row);

    // Capture results while Stage 3 outputs are stable
    psout = PSOUT;
    quant = {RES_OUT, SOUT};    // reassemble 4-bit result from its two output ports
  endtask

  // ---------------------------------------------------------------------------
  // compute_all_rows_pipelined — back-to-back triggers, one per cycle.
  //
  // Fires one compute trigger per cycle for all NB_KERNEL_ROWS rows, then
  // collects results as they emerge 4 cycles later in the same loop.
  //
  //   Trigger phase  cycles  0 .. NB_KERNEL_ROWS-1 : COMPE=1, RA steps each cycle
  //   Overlap        cycles  4 .. NB_KERNEL_ROWS-1 : trigger + capture simultaneously
  //   Drain phase    cycles  NB_KERNEL_ROWS .. NB_KERNEL_ROWS+3 : COMPE=0, flush last 4
  //
  //   Total: NB_KERNEL_ROWS+4 cycles  (36 for 32 rows vs 128 in the serial approach)
  //
  // IMPORTANT: MCT is read from the live port inside the DUT (not pipelined).
  // mct_val must stay constant — do not use this task for per-row MCT sweeps.
  // ---------------------------------------------------------------------------
  task automatic compute_all_rows_pipelined(
    input  [23:0] bias,
    input  [7:0]  mct_val,
    output [23:0] psout_out [0:NB_KERNEL_ROWS-1],
    output [3:0]  quant_out [0:NB_KERNEL_ROWS-1]
  );
    for (int i = 0; i < NB_KERNEL_ROWS + 4; i++) begin
      @(posedge RCK); #ApplTime;

      if (i < NB_KERNEL_ROWS) begin
        COMPE = 1'b1;
        MODE  = 2'b11;
        MCT   = mct_val;
        RA    = {5'(i), 2'b00};
        ADDIN = bias;
        RCSN  = 1'b0; RCSN0 = 1'b0; RCSN1 = 1'b0; RCSN2 = 1'b0; RCSN3 = 1'b0;
        WCSN  = 1'b1; WEN   = 1'b1; FCSN  = 1'b1;
      end else begin
        COMPE = 1'b0;
        RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
      end

      // when i = ? -- exactly 5 pos edges already happened since the request was made 
      // as per the test bench, posedge happends and then 
      if (i >= 5) begin
        #(TestTime - ApplTime);
        if (READYN !== 1'b0)
          $error("[TB] READYN not low at pipelined result cycle for row %0d", i - 5);
        psout_out[i - 5] = PSOUT;
        quant_out[i - 5] = {RES_OUT, SOUT};
      end
    end

    @(posedge RCK); #ApplTime;
    COMPE = 1'b0;
    RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
  endtask

  // =========================================================================
  // PASS / FAIL COUNTERS
  // =========================================================================
  // Each test increments exactly one counter.  The final summary displays
  // both counts so you can see overall pass/fail at a glance.
  int pass_count = 0;
  int fail_count = 0;

  // =========================================================================
  // MAIN TEST SEQUENCE
  // =========================================================================
  initial begin
    // Local variables used across multiple tests
    logic [SECTION_WIDTH-1:0] rd_data;                 // captured kernel readback data
    logic [23:0]              psout, psout_expected;   // psum from DUT and golden
    logic [3:0]               quant, quant_expected;   // 4-bit result from DUT and golden
    logic [23:0]              psout_pipe [0:NB_KERNEL_ROWS-1];  // per-row psum captured by Test 6
    logic [3:0]               quant_pipe [0:NB_KERNEL_ROWS-1]; // per-row quant captured by Test 6

    // Wait for reset to release (driven by the clock initial block)
    @(posedge RESETn);
    // One extra idle cycle so all DUT output registers settle cleanly from reset
    @(posedge RCK);

    // -----------------------------------------------------------------------
    // Load all stimulus and golden data from files generated by gen_stim.py.
    //
    // All files use $readmemh-compatible hexadecimal:
    //   - 256-bit sections: 64 hex chars per line, MSB first (byte 31 first)
    //   - 4-bit results:    2 hex chars per line, result in lower nibble
    //   - 24-bit psums:     6 hex chars per line
    // -----------------------------------------------------------------------
    $readmemh(KERNEL_WEIGHTS_FILE,        kernel_stim);    // 128 entries: 32 rows × 4 sections
    $readmemh(FEATURE_VECTOR_FILE,        feature_stim);   //   4 entries: one per 256-bit section
    $readmemh(GOLDEN_MATVEC_FILE,          golden_matvec);  //  32 entries: expected 4-bit result per row
    $readmemh(GOLDEN_PSOUT_FILE,           golden_psout);   //  32 entries: expected 24-bit psum per row
    $readmemh(GOLDEN_DOT_PRODUCT_MCT_FILE, golden_mct);     //   6 entries: 4-bit result for row 0 per MCT
    $readmemh(GOLDEN_PSOUT_MCT_FILE,       golden_psout_mct); // 6 entries: 24-bit psum for row 0 per MCT

    // =======================================================================
    // TEST 5: RESET VERIFICATION
    // =======================================================================
    // After RESETn releases, the DUT should hold every output and every
    // internal memory location at zero (except READYN which should be 1,
    // meaning "not ready", since no compute has been triggered).
    //
    // Checks performed:
    //   READYN == 1   (no spurious ready signal)
    //   PSOUT  == 0   (psum register cleared)
    //   {RES_OUT, SOUT} == 0  (quantized output cleared)
    //   Q == 0        (memory read output cleared)
    //   feature_buf[0..3] == 0  (feature buffer cleared, via hierarchical ref)
    //   kernel_mem[0..31][0..3] == 0  (SRAM cleared, via hierarchical ref)
    //
    // Hierarchical references (i_dut.feature_buf, i_dut.kernel_mem) are used
    // because these internal memories have no dedicated read port for direct
    // external access — the only way to see them from the testbench is to
    // look directly inside the DUT's hierarchy.
    // =======================================================================
    $display("[TB] Test 5: Reset verification");
    @(posedge RCK); #TestTime;

    begin
      automatic logic reset_ok = 1'b1;
      if (READYN !== 1'b1)         reset_ok = 1'b0;   // must be NOT-ready
      if (PSOUT  !== 24'h0)        reset_ok = 1'b0;   // psum cleared
      if ({RES_OUT,SOUT} !== 4'h0) reset_ok = 1'b0;   // quant output cleared
      if (Q !== '0)                reset_ok = 1'b0;   // memory read port cleared
      // Check feature buffer via hierarchical reference (no external read port)
      for (int s = 0; s < 4; s++)
        if (i_dut.feature_buf[s] !== '0) reset_ok = 1'b0;
      // Check kernel SRAM via hierarchical reference (32 rows × 4 sections)
      for (int r = 0; r < NB_KERNEL_ROWS; r++)
        for (int s = 0; s < 4; s++)
          if (i_dut.kernel_mem[r][s] !== '0) reset_ok = 1'b0;
      if (!reset_ok) begin $error("[TB] Test5 FAIL: one or more signals not zero/one after reset"); fail_count++; end
      else           begin $display("[TB] Test 5: PASS"); pass_count++; end
    end

    // =======================================================================
    // TEST 1: KERNEL WRITE + READ-BACK
    // =======================================================================
    // Writes every section of every kernel row using write_kernel, then
    // immediately reads it back with read_kernel and compares Q against
    // what was written.  This verifies the SRAM's read and write paths
    // independently of the compute pipeline.
    //
    // 32 rows × 4 sections = 128 write+readback pairs.
    // A single failure counter tracks all mismatches; the test passes only
    // if every readback exactly matches what was written.
    // =======================================================================
    $display("[TB] Test 1: Kernel write + read-back");
    begin
      automatic int test_fail = 0;
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          write_kernel(5'(r), 2'(s), kernel_stim[r*4 + s]);   // write one section
          read_kernel(5'(r), 2'(s), rd_data);                  // read it back
          if (rd_data !== kernel_stim[r*4 + s]) begin
            $error("[TB] Test1 row%0d sec%0d: got 0x%h, expected 0x%h",
                   r, s, rd_data, kernel_stim[r*4 + s]);
            test_fail++;
          end
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 1: PASS"); pass_count++; end
      else                begin $display("[TB] Test 1: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end

    // =======================================================================
    // TEST 2: LOAD FEATURE VECTOR
    // =======================================================================
    // Writes the 4 × 256-bit feature vector sections into the DUT's internal
    // feature buffer.  There is no external read port on the feature buffer,
    // so this test cannot verify correctness directly.  Correct loading is
    // confirmed indirectly by the compute results in Test 3.
    //
    // After this task returns, the DUT's feature_buf holds the complete
    // 1024-bit feature vector that will be used for all subsequent MACs.
    // =======================================================================
    $display("[TB] Test 2: Load feature vector");
    load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);

    // =======================================================================
    // TEST 3: FULL MATRIX-VECTOR MULTIPLICATION (32 rows, MCT=0)
    // =======================================================================
    // Exercises the full MAC pipeline for every kernel row.
    //
    //   Computes for each row r:
    //     psum[r]  = dot(kernel[r], feature, MCT=0) + BIAS   (24-bit, all 128 elements active)
    //     quant[r] = ReLU4(psum[r])                           (4-bit clipped result)
    //
    // Both outputs must match the golden files produced by gen_stim.py:
    //   golden_psout[r]  — 24-bit psum before ReLU (from golden_psout.txt)
    //   golden_matvec[r] — 4-bit quantized result (from golden_matvec.txt)
    //
    // MCT=0 means no masking: all 128 byte-elements of every row participate.
    // The kernel and feature are already loaded by Tests 1 and 2.
    // =======================================================================
    $display("[TB] Test 3: Full matrix-vector multiplication (32 rows)");
    begin
      automatic int test_fail = 0;
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        compute_and_capture(5'(r), BIAS, 8'd0, psout, quant);
        // Check both the raw psum and the quantized output independently
        if (psout !== golden_psout[r] || quant !== golden_matvec[r][3:0]) begin
          if (psout !== golden_psout[r])
            $error("[TB] Test3 row%0d: psout got 0x%06h, expected 0x%06h", r, psout, golden_psout[r]);
          if (quant !== golden_matvec[r][3:0])
            $error("[TB] Test3 row%0d: quant got %0d, expected %0d", r, quant, golden_matvec[r][3:0]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 3: PASS"); pass_count++; end
      else                begin $display("[TB] Test 3: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end

    // =======================================================================
    // TEST 4: MCT MASKING SWEEP
    // =======================================================================
    // Verifies that the MCT masking hardware correctly trims the number of
    // active byte-elements in the dot product for row 0.
    //
    // Row 0 is computed once for each of the 6 MCT values in MCT_VALS:
    //   MCT=  0 → 128 active elements (full row, no masking)
    //   MCT=128 →  64 active elements (lower half of the row)
    //   MCT=192 →  32 active elements (first section only)
    //   MCT=224 →  16 active elements
    //   MCT=240 →   8 active elements
    //   MCT=248 →   4 active elements (almost fully masked)
    //
    // Expected results come from golden_dot_product_mct.txt (4-bit quant)
    // and golden_psout_mct.txt (24-bit psum before ReLU), both generated
    // by gen_stim.py using the same MCT masking logic as the DUT.
    //
    // The kernel and feature are still in the DUT from Tests 1 and 2.
    // =======================================================================
    $display("[TB] Test 4: MCT masking sweep (%0d values, row 0)", NB_MCT_VALS);
    begin
      automatic logic [23:0] psout;
      automatic logic [3:0]  quant;

      automatic int test_fail = 0;
      for (int m = 0; m < NB_MCT_VALS; m++) begin
        compute_and_capture(5'd0, BIAS, MCT_VALS[m], psout, quant);
        if (psout !== golden_psout_mct[m] || quant !== golden_mct[m][3:0]) begin
          if (psout !== golden_psout_mct[m])
            $error("[TB] Test4 MCT=0x%02h row0: psout got 0x%06h, expected 0x%06h",
                   MCT_VALS[m], psout, golden_psout_mct[m]);
          if (quant !== golden_mct[m][3:0])
            $error("[TB] Test4 MCT=0x%02h row0: quant got %0d, expected %0d",
                   MCT_VALS[m], quant, golden_mct[m][3:0]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 4: PASS"); pass_count++; end
      else                begin $display("[TB] Test 4: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end

    // =======================================================================
    // TEST 6: PIPELINED MATRIX-VECTOR MULTIPLICATION (32 rows, MCT=0)
    // =======================================================================
    // Self-contained: re-loads kernel weights and feature vector, then fires
    // one trigger per cycle for all 32 rows and collects results in 36 cycles.
    //
    // Throughput: 36 cycles vs 128 cycles in Test 3 (~3.6x faster).
    // Results are verified against the same golden files used by Test 3.
    // =======================================================================
    $display("[TB] Test 6: Pipelined matrix-vector multiplication (32 rows)");
    begin
      automatic int test_fail = 0;

      // Re-load kernel weights (32 rows x 4 sections)
      for (int r = 0; r < NB_KERNEL_ROWS; r++)
        for (int s = 0; s < 4; s++)
          write_kernel(5'(r), 2'(s), kernel_stim[r*4 + s]);

      // Re-load feature vector
      load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);

      // Fire all 32 rows back-to-back and collect results
      compute_all_rows_pipelined(BIAS, 8'd0, psout_pipe, quant_pipe);

      // Display and verify all results
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        $display("[TB] Test6 row%02d: psout=0x%06h quant=%0d (expected psout=0x%06h quant=%0d)",
                 r, psout_pipe[r], quant_pipe[r], golden_psout[r], golden_matvec[r][3:0]);
        $display("psout_pipe[%02d] = 0x%06h", r, psout_pipe[r]);
        if (psout_pipe[r] !== golden_psout[r] || quant_pipe[r] !== golden_matvec[r][3:0]) begin
          if (psout_pipe[r] !== golden_psout[r])
            $error("[TB] Test6 row%0d: psout got 0x%06h, expected 0x%06h", r, psout_pipe[r], golden_psout[r]);
          if (quant_pipe[r] !== golden_matvec[r][3:0])
            $error("[TB] Test6 row%0d: quant got %0d, expected %0d", r, quant_pipe[r], golden_matvec[r][3:0]);
          test_fail++;
        end
        
      end
      if (test_fail == 0) begin $display("[TB] Test 6: PASS"); pass_count++; end
      else                begin $display("[TB] Test 6: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end

    // =======================================================================
    // FINAL SUMMARY
    // =======================================================================
    $display("[TB] ================================================");
    $display("[TB] RESULTS: %0d PASSED, %0d FAILED", pass_count, fail_count);
    $display("[TB] ================================================");
    if (fail_count == 0) $display("[TB] ALL TESTS PASSED");
    else                  $display("[TB] FAILURES DETECTED");
    $display("Testbench: Test finished.");
    eot = 1'b1;   // signal completion to any external watcher
    $finish;
  end

  // =========================================================================
  // WAVEFORM DUMP
  // =========================================================================
  // Dumps all signals to a VCD file for viewing in GTKWave or ModelSim.
  // The depth=0 argument to $dumpvars captures the full hierarchy including
  // DUT internals (pipeline registers, memories, etc.).
  initial begin
    $dumpfile("tb_DIMC_18_fixed.vcd");
    $dumpvars(0, tb_DIMC_18_fixed);
  end

  // =========================================================================
  // WATCHDOG TIMER
  // =========================================================================
  // Kills the simulation after 50 µs (5000 clock cycles at 100 MHz).
  // This prevents the simulation from hanging indefinitely if the DUT
  // never asserts READYN or a task gets stuck waiting for a clock edge.
  // Normal simulation takes far fewer than 5000 cycles, so a watchdog
  // trip always indicates a bug.
  initial begin
    #(5000 * ClkPeriod);
    $error("[TB] WATCHDOG: simulation exceeded 50 us");
    $finish;
  end

endmodule

// =============================================================================
// Running the test bench
// =============================================================================
// cd hw/ip/spatz/tb
// python3 gen_stim.py --seed 14
// module load questasim
// vlib work
// vlog -sv ../src/spatz_DIMC.sv tb_DIMC_18_fixed.sv
// vsim -c tb_DIMC_18_fixed -do "run -all; quit"
