/*
 * tb_spatz_dimc.sv
 *
 * PURPOSE
 * Testbench for the spatz_dimc module (defined in spatz_dimc.sv).
 *
 * TEST STRUCTURE
 * All stimulus  and golden outputs are generated by spatz_dimc_stim.py
 *
 * Test 1 — Reset: verify all DUT outputs and memories are zero
 * Test 2 — Kernel write + readback: 32 rows × 4 sections
 * Test 3 — Optimized kernel write + readback
 * Test 4 — Concurrent kernel read and write through independent ports
 * Test 5 — Load feature vector, then run Full MatVec for all 32 rows
 * Test 6 — Pipelined Full MatVec
 * Test 7 — compute_mask sweep: row 0 at 6 different compute_mask values
 * Test 8 — Signed 8-bit multiplication: sign_8b=01, 10, and 11
 *
 * ============================================================
 * TO RUN SIMULATION
 * ============================================================
 *  make hw-clean
 *  make hw-all
 *  make sim-single
 */

// ── Test enable macros ────────────────────────────────────────────────────
// Comment out a line to skip that test at compile time.
`define tb_dimc_TEST1    // Reset verification
`define tb_dimc_TEST2    // Kernel write + read-back
`define tb_dimc_TEST3    // Optimized kernel write + read-back
`define tb_dimc_TEST4    // Concurrent dual-port read and write
`define tb_dimc_TEST5    // Feature load + Full MatVec
`define tb_dimc_TEST6    // Pipelined Full MatVec
`define tb_dimc_TEST7    // compute_mask masking sweep
`define tb_dimc_TEST8    // Signed 8-bit multiplication
`define tb_dimc_TEST9    // different precision multiplication (2-bit, 4-bit, 8-bit)
// ─────────────────────────────────────────────────────────────────────────

`timescale 1ns/1ps

module tb_dimc;

  // -------------------------------------------------------------------------
  // Parameters
  // -------------------------------------------------------------------------
  // SECTION_WIDTH: Memory is divided to 4 sections, each 256 bits wide.
  parameter SECTION_WIDTH  = 256;

  // NB_KERNEL_ROWS: the DUT stores 32 rows of kernel weights.
  parameter NB_KERNEL_ROWS = 32;

  // Stimulus files produced by spatz_dimc_stim.py.
  // They must be present before running testbench.
  parameter KERNEL_WEIGHTS_FILE        = "stimuli/spatz_dimc_stims/kernel_weights.txt";       // File 1
  parameter FEATURE_VECTOR_FILE        = "stimuli/spatz_dimc_stims/feature_vector.txt";       // File 2
  parameter GOLDEN_MATVEC_FILE          = "stimuli/spatz_dimc_stims/golden_clipped_8bit.txt";
  parameter GOLDEN_PSOUT_FILE           = "stimuli/spatz_dimc_stims/golden_psum_32bit.txt";
  parameter GOLDEN_COMPUTE_MASK_FILE    = "stimuli/spatz_dimc_stims/golden_with_masking_8bit.txt";
  parameter GOLDEN_PSOUT_MASK_FILE      = "stimuli/spatz_dimc_stims/golden_psum_with_masking_32bit.txt";
  
  parameter GOLDEN_SIGN_01_CLIPPED_FILE = "stimuli/spatz_dimc_stims/golden_sign_01_clipped_8bit.txt";
  parameter GOLDEN_SIGN_01_PSOUT_FILE   = "stimuli/spatz_dimc_stims/golden_sign_01_psum_32bit.txt";
  parameter GOLDEN_SIGN_10_CLIPPED_FILE = "stimuli/spatz_dimc_stims/golden_sign_10_clipped_8bit.txt";
  parameter GOLDEN_SIGN_10_PSOUT_FILE   = "stimuli/spatz_dimc_stims/golden_sign_10_psum_32bit.txt";
  parameter GOLDEN_SIGN_11_CLIPPED_FILE = "stimuli/spatz_dimc_stims/golden_sign_11_clipped_8bit.txt";
  parameter GOLDEN_SIGN_11_PSOUT_FILE   = "stimuli/spatz_dimc_stims/golden_sign_11_psum_32bit.txt";

  parameter GOLDEN_MODE_00_CLIPPED_FILE = "stimuli/spatz_dimc_stims/golden_mode_00_clipped_8bit.txt";
  parameter GOLDEN_MODE_00_PSOUT_FILE   = "stimuli/spatz_dimc_stims/golden_mode_00_psum_32bit.txt";
  parameter GOLDEN_MODE_01_CLIPPED_FILE = "stimuli/spatz_dimc_stims/golden_mode_01_clipped_8bit.txt";
  parameter GOLDEN_MODE_01_PSOUT_FILE   = "stimuli/spatz_dimc_stims/golden_mode_01_psum_32bit.txt";
  parameter GOLDEN_MODE_10_CLIPPED_FILE = "stimuli/spatz_dimc_stims/golden_mode_10_clipped_8bit.txt";
  parameter GOLDEN_MODE_10_PSOUT_FILE   = "stimuli/spatz_dimc_stims/golden_mode_10_psum_32bit.txt";


  /*  maksking parameters
      Must equal len(COMPUTE_MASK_VALS) in spatz_dimc_stim.py.
  */
  // NB_COMPUTE_MASK_VALS: how many distinct compute_mask values are swept in Test 7.
  parameter NB_COMPUTE_MASK_VALS = 6;
  // COMPUTE_MASK_VALS: the six threshold values swept in Test 7.
  localparam logic [9:0] COMPUTE_MASK_VALS [NB_COMPUTE_MASK_VALS] =
      '{10'd0, 10'd512, 10'd768, 10'd896, 10'd960, 10'd992};


  localparam logic [31:0] BIAS = 32'd0;

  // Stimulus and golden arrays
  // These are filled by $readmemh at the start of the test sequence.
  logic [SECTION_WIDTH-1:0] kernel_stim  [0 : NB_KERNEL_ROWS*4-1];

  // feature_stim: the 1024-bit feature vector split into 4 × 256-bit sections.
  //   feature_stim[0] = bits [255:0], feature_stim[3] = bits [1023:768].
  logic [SECTION_WIDTH-1:0] feature_stim [0 : 3];

  logic [7:0]  golden_clipped  [0 : NB_KERNEL_ROWS-1];

  logic [31:0] golden_psout   [0 : NB_KERNEL_ROWS-1];

  logic [7:0]  golden_compute_mask [0 : NB_COMPUTE_MASK_VALS-1];

  logic [31:0] golden_psout_compute_mask[0 : NB_COMPUTE_MASK_VALS-1];

  logic [7:0]  golden_sign_01_clipped [0 : NB_KERNEL_ROWS-1];
  logic [31:0] golden_sign_01_psout   [0 : NB_KERNEL_ROWS-1];
  logic [7:0]  golden_sign_10_clipped [0 : NB_KERNEL_ROWS-1];
  logic [31:0] golden_sign_10_psout   [0 : NB_KERNEL_ROWS-1];
  logic [7:0]  golden_sign_11_clipped [0 : NB_KERNEL_ROWS-1];
  logic [31:0] golden_sign_11_psout   [0 : NB_KERNEL_ROWS-1];

  logic [7:0]  golden_mode_00_clipped [0 : NB_KERNEL_ROWS-1];
  logic [31:0] golden_mode_00_psout   [0 : NB_KERNEL_ROWS-1];
  logic [7:0]  golden_mode_01_clipped [0 : NB_KERNEL_ROWS-1];
  logic [31:0] golden_mode_01_psout   [0 : NB_KERNEL_ROWS-1];
  logic [7:0]  golden_mode_10_clipped [0 : NB_KERNEL_ROWS-1];
  logic [31:0] golden_mode_10_psout   [0 : NB_KERNEL_ROWS-1];


  // Timing parameters
  localparam time ClkPeriod = 10ns;
  localparam time WClkPeriod = 14ns;
  localparam time ApplTime  =  2ns;
  localparam time TestTime  =  8ns;
  localparam NUM_SECTIONS = 1024 / SECTION_WIDTH;
  localparam ROW_WIDTH    = 1024;

  // =========================================================================
  // DUT SIGNAL DECLARATIONS
  // =========================================================================
  logic RCK;
  logic RESETn = 1'b1;

  logic        READYN;
  logic        COMPE  = 1'b0;
  logic        FCSN   = 1'b1;
  logic [1:0]  MODE   = 2'b11;

  logic [1:0]               FA    = '0;
  logic [SECTION_WIDTH-1:0] FD    = '0;

  logic [31:0]              ADDIN = '0;
  logic [7:0]               SOUT;
  logic [31:0]              PSOUT;
  logic [SECTION_WIDTH-1:0] Q;
  logic [SECTION_WIDTH-1:0] D     = '0;
  logic [6:0]               RA    = '0;
  logic [6:0]               WA    = '0;
  logic RCSN  = 1'b1;

  logic RCSN0 = 1'b1;
  logic RCSN1 = 1'b1;
  logic RCSN2 = 1'b1;
  logic RCSN3 = 1'b1;

  logic WCK;
  logic WCSN  = 1'b1;

  logic WEN   = 1'b1;

  logic [SECTION_WIDTH-1:0] M   = '1;

  logic [9:0]               compute_mask = '0;
  logic [1:0]               sign_8b = 2'b00;

  // End-of-test flag
  logic eot = 1'b0;

  spatz_dimc #(
    .SECTION_WIDTH (SECTION_WIDTH)
  ) i_dut (
    .RCK     (RCK),
    .RESETn  (RESETn),
    .READYN  (READYN),
    .COMPE   (COMPE),
    .FCSN    (FCSN),
    .MODE    (MODE),
    .FA      (FA),
    .FD      (FD),
    .ADDIN   (ADDIN),
    .SOUT    (SOUT),
    .PSOUT   (PSOUT),
    .Q       (Q),
    .D       (D),
    .RA      (RA),
    .WA      (WA),
    .RCSN    (RCSN),
    .RCSN0   (RCSN0),
    .RCSN1   (RCSN1),
    .RCSN2   (RCSN2),
    .RCSN3   (RCSN3),
    .WCK     (WCK),
    .WCSN    (WCSN),
    .WEN     (WEN),
    .M       (M),
    .compute_mask(compute_mask),
    .sign_8b (sign_8b)
  );

  // READ CLOCK GENERATION
  initial begin
    RCK = 1'b0;
    forever #(ClkPeriod/2) RCK = ~RCK;
  end

  // Independent kernel-memory write clock.
  initial begin
    WCK = 1'b0;
    forever #(WClkPeriod/2) WCK = ~WCK;
  end

  task automatic reset_dimc;
    RESETn = 1'b0;
    COMPE = 1'b0; FCSN = 1'b1; RCSN = 1'b1;
    RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
    WCSN = 1'b1; WEN = 1'b1;
    D = '0; FD = '0; M = '1;
    MODE = 2'b11; compute_mask = '0; sign_8b = 2'b00; ADDIN = '0;
    repeat (2) @(posedge RCK);
    #ApplTime RESETn = 1'b1;
    @(posedge RCK); #ApplTime;
  endtask

  task automatic write_kernel_section(
    input [4:0]               row,   // which of the 32 kernel rows to write
    input [1:0]               sec,   // which 256-bit section within that row (0-3)
    input [SECTION_WIDTH-1:0] data   // the 256-bit data to write
  );
    @(posedge WCK); #ApplTime;
    // Keep the read port and feature-buffer write path idle so this task
    // verifies only the kernel-memory write operation.
    COMPE = 1'b0; WA = {row, sec}; D = data; M = '1;
    WCSN = 1'b0; WEN = 1'b0; RCSN = 1'b1; FCSN = 1'b1;

    @(posedge WCK); #ApplTime;   // this WCK edge latches the write
    WCSN = 1'b1; WEN = 1'b1;    // deassert; clear data bus
    D = '0;
  endtask

 task automatic write_full_kernel(
    input [SECTION_WIDTH-1:0] data [0:NB_KERNEL_ROWS*4-1]   // 128 × 256-bit sections
  );
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          @(negedge WCK);
          COMPE = 1'b0; WA = {5'(r), 2'(s)}; D = data[r*4 + s]; M = '1;
          WCSN = 1'b0; WEN = 1'b0; RCSN = 1'b1; FCSN = 1'b1;
          @(posedge WCK); #ApplTime;
          WCSN = 1'b1; WEN = 1'b1;
        end
      end

      // Clear the write data after the last WCK transaction.
      D = '0;
  endtask

  task automatic read_kernel(
    input  [4:0]               row,    // row to read
    input  [1:0]               sec,    // section within that row (0-3)
    output [SECTION_WIDTH-1:0] rdata   // captured output from Q port
  );
    @(posedge RCK); #ApplTime;
    COMPE = 1'b0; RCSN = 1'b0; RA = {row, sec};
    WCSN = 1'b1; WEN = 1'b1; FCSN = 1'b1;   // ensure write and feature paths are idle

    @(posedge RCK); #TestTime;   // Q is registered at this posedge; stable by +TestTime
    rdata = Q;
    RCSN  = 1'b1;   // deassert read enable
  endtask

task automatic load_feature(
    input [SECTION_WIDTH-1:0] f0,   // section 0: bits [255:0]
    input [SECTION_WIDTH-1:0] f1,   // section 1: bits [511:256]
    input [SECTION_WIDTH-1:0] f2,   // section 2: bits [767:512]
    input [SECTION_WIDTH-1:0] f3    // section 3: bits [1023:768]
  );
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd0; FD = f0;  // latch section 0
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd1; FD = f1;  // latch section 1
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd2; FD = f2;  // latch section 2
    @(posedge RCK); #ApplTime; FCSN = 1'b0; FA = 2'd3; FD = f3;  // latch section 3
    @(posedge RCK); #ApplTime; FCSN = 1'b1; FD = '0;              // deassert; buffer retains values
  endtask


  task automatic compute_and_capture(
    input  [4:0]  row,      // kernel row to compute dot product for (0-31)
    input  [31:0] bias,
    input  [9:0]  compute_mask_val,
    input  [1:0]  sign_mode,
    input  [1:0]  mode,
    output [31:0] psout,
    output [7:0]  clipped
  );
    // --- Cycle N: assert compute trigger for exactly one cycle ---
    @(posedge RCK); #ApplTime;
    COMPE = 1'b1;                             // trigger the pipeline
    MODE  = mode;                             // MAC mode
    compute_mask = compute_mask_val;
    sign_8b = sign_mode;
    RA    = {row, 2'b00};                     // row address; section bits ignored in compute mode
    ADDIN = bias;                             // bias to add at Stage 3
    RCSN  = 1'b0; RCSN0 = 1'b0; RCSN1 = 1'b0; RCSN2 = 1'b0; RCSN3 = 1'b0;  // enable all sections
    WCSN  = 1'b1; WEN   = 1'b1; FCSN  = 1'b1;   // write and feature paths must be idle

    // --- Cycle N+1: deassert trigger; Stage 0 captures inputs ---
    @(posedge RCK); #ApplTime;
    COMPE = 1'b0;
    RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;

    // --- Cycles N+2 and N+3: pipeline progresses through Stages 1 and 2 ---
    @(posedge RCK);   // Stage 1: computation masking
    @(posedge RCK);   // Stage 2: MAC accumulation

    // --- Cycle N+4: Stage 3 completes; READYN should now be LOW ---
    @(posedge RCK); #TestTime;
    if (READYN !== 1'b0)
      $error("[TB] READYN did not go low after 4-cycle pipeline latency (row=%0d)", row);

    // Capture results while Stage 3 outputs are stable
    psout = PSOUT;
    clipped = SOUT;
  endtask


  task automatic compute_all_rows_pipelined(
    input  [31:0] bias,
    input  [9:0]  compute_mask_val,
    input  [1:0]  sign_mode,
    input  [1:0]  mode,
    output [31:0] psout_out [0:NB_KERNEL_ROWS-1],
    output [7:0]  clipped_out [0:NB_KERNEL_ROWS-1]
  );
    for (int i = 0; i < NB_KERNEL_ROWS + 4; i++) begin
      @(posedge RCK); #ApplTime;

      if (i < NB_KERNEL_ROWS) begin
        COMPE = 1'b1;
        MODE  = mode;
        compute_mask = compute_mask_val;
        sign_8b = sign_mode;
        RA    = {5'(i), 2'b00};
        ADDIN = bias;
        RCSN  = 1'b0; RCSN0 = 1'b0; RCSN1 = 1'b0; RCSN2 = 1'b0; RCSN3 = 1'b0;
        WCSN  = 1'b1; WEN   = 1'b1; FCSN  = 1'b1;
      end else begin
        COMPE = 1'b0;
        RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
      end

      // The result for request 0 is available when i=4. Subsequent
      // back-to-back requests produce one result per cycle.
      if (i >= 4) begin
        #(TestTime - ApplTime);
        if (READYN !== 1'b0)
          $error("[TB] READYN not low at pipelined result cycle for row %0d", i - 4);
        psout_out[i - 4] = PSOUT;
        clipped_out[i - 4] = SOUT;
      end
    end

    @(posedge RCK); #ApplTime;
    COMPE = 1'b0;
    RCSN  = 1'b1; RCSN0 = 1'b1; RCSN1 = 1'b1; RCSN2 = 1'b1; RCSN3 = 1'b1;
  endtask


  // PASS / FAIL COUNTERS
  int pass_count = 0;
  int fail_count = 0;

  // =========================================================================
  // MAIN TEST SEQUENCE
  // =========================================================================
  initial begin
    // Local variables used across multiple tests
    logic [SECTION_WIDTH-1:0] rd_data;                 // captured kernel readback data
    logic [31:0]              psout, psout_expected;
    logic [7:0]               clipped, clipped_expected;
    logic [31:0]              psout_pipe [0:NB_KERNEL_ROWS-1];
    logic [7:0]               clipped_pipe [0:NB_KERNEL_ROWS-1];

    $readmemh(KERNEL_WEIGHTS_FILE,        kernel_stim);    // 128 entries: 32 rows × 4 sections
    $readmemh(FEATURE_VECTOR_FILE,        feature_stim);   //   4 entries: one per 256-bit section
    $readmemh(GOLDEN_MATVEC_FILE,          golden_clipped);  // 32 expected clipped 8-bit results
    $readmemh(GOLDEN_PSOUT_FILE,           golden_psout);   //  32 entries: expected 32-bit psum per row
    $readmemh(GOLDEN_COMPUTE_MASK_FILE, golden_compute_mask);
    $readmemh(GOLDEN_PSOUT_MASK_FILE, golden_psout_compute_mask);

    $readmemh(GOLDEN_SIGN_01_CLIPPED_FILE, golden_sign_01_clipped);
    $readmemh(GOLDEN_SIGN_01_PSOUT_FILE, golden_sign_01_psout);
    $readmemh(GOLDEN_SIGN_10_CLIPPED_FILE, golden_sign_10_clipped);
    $readmemh(GOLDEN_SIGN_10_PSOUT_FILE, golden_sign_10_psout);
    $readmemh(GOLDEN_SIGN_11_CLIPPED_FILE, golden_sign_11_clipped);
    $readmemh(GOLDEN_SIGN_11_PSOUT_FILE, golden_sign_11_psout);
    
    $readmemh(GOLDEN_MODE_00_CLIPPED_FILE, golden_mode_00_clipped);
    $readmemh(GOLDEN_MODE_00_PSOUT_FILE, golden_mode_00_psout);
    $readmemh(GOLDEN_MODE_01_CLIPPED_FILE, golden_mode_01_clipped);
    $readmemh(GOLDEN_MODE_01_PSOUT_FILE, golden_mode_01_psout);
    $readmemh(GOLDEN_MODE_10_CLIPPED_FILE, golden_mode_10_clipped);
    $readmemh(GOLDEN_MODE_10_PSOUT_FILE, golden_mode_10_psout);
    

`ifdef tb_dimc_TEST1
    // =======================================================================
    // TEST 1: RESET VERIFICATION
    // =======================================================================
    // Purpose: Verify reset clears DUT state and deasserts output-valid.
    // Verification: Check outputs and feature buffer, then read every kernel section through Q.
    // =======================================================================
    $display("[TB] Test 1: Reset verification");
    reset_dimc();
    @(posedge RCK); #TestTime;

    begin
      automatic logic reset_ok = 1'b1;
      if (READYN !== 1'b1)         reset_ok = 1'b0;   // must be NOT-ready
      if (PSOUT !== 32'h0) reset_ok = 1'b0;
      if (SOUT  !== 8'h0)  reset_ok = 1'b0;
      if (Q !== '0)                reset_ok = 1'b0;   // memory read port cleared
      // Check feature buffer via hierarchical reference (no external read port)
      for (int s = 0; s < 4; s++)
        if (i_dut.feature_buf[s] !== '0) reset_ok = 1'b0;
      // Check every kernel section through the external read port Q.
      for (int r = 0; r < NB_KERNEL_ROWS; r++)
        for (int s = 0; s < 4; s++) begin
          read_kernel(5'(r), 2'(s), rd_data);
          if (rd_data !== '0) reset_ok = 1'b0;
        end
      if (!reset_ok) begin $error("[TB] Test1 FAIL: one or more signals not zero/one after reset"); fail_count++; end
      else           begin $display("[TB] Test 1: PASS"); pass_count++; end
    end
`endif // tb_dimc_TEST1



`ifdef tb_dimc_TEST2
    // =======================================================================
    // TEST 2: KERNEL WRITE + READ-BACK
    // =======================================================================
    // Purpose: Verify individual kernel-section writes and reads.
    // Verification: Write each section, immediately read Q, and compare with the stimulus.
    // =======================================================================
    $display("[TB] Test 2: Kernel write + read-back");
    reset_dimc();
    begin
      automatic int test_fail = 0;
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          write_kernel_section(5'(r), 2'(s), kernel_stim[r*4 + s]);   // write one section
          read_kernel(5'(r), 2'(s), rd_data);                  // read it back
          if (rd_data !== kernel_stim[r*4 + s]) begin
            $error("[TB] Test2 row%0d sec%0d: got 0x%h, expected 0x%h",
                   r, s, rd_data, kernel_stim[r*4 + s]);
            test_fail++;
          end
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 2: PASS"); pass_count++; end
      else                begin $display("[TB] Test 2: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST2

`ifdef tb_dimc_TEST3
    // =======================================================================
    // TEST 3: efficient version of KERNEL WRITE + READ-BACK
    // =======================================================================
    // Purpose: Verify consecutive full-kernel writes.
    // Verification: Write all sections first, then read Q and compare every section.
    // =======================================================================
    $display("[TB] Test 3: optimized Kernel write + read-back");
    reset_dimc();
    begin
      automatic int     test_fail = 0;
      automatic longint t_start, t_end;
      @(posedge WCK); t_start = $time;
      write_full_kernel(kernel_stim);
      t_end = $time;
      $display("[TB] Test 3: full-kernel write took %0d WCK cycles",
               (t_end - t_start + WClkPeriod/2) / WClkPeriod);
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        for (int s = 0; s < 4; s++) begin
          read_kernel(5'(r), 2'(s), rd_data);                  // read it back
          if (rd_data !== kernel_stim[r*4 + s]) begin
            $error("[TB] Test3 row%0d sec%0d: got 0x%h, expected 0x%h",
                   r, s, rd_data, kernel_stim[r*4 + s]);
            test_fail++;
          end
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 3: PASS"); pass_count++; end
      else                begin $display("[TB] Test 3: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST3

`ifdef tb_dimc_TEST4
    // =======================================================================
    // TEST 4: CONCURRENT DUAL-PORT READ + WRITE
    // =======================================================================
    // Purpose: Verify concurrent kernel read and write on independent ports.
    // Verification: Read section 0 through Q while writing section 1, then check both results.
    // =======================================================================
    $display("[TB] Test 4: Concurrent dual-port kernel read + write");
    reset_dimc();
    begin
      automatic int test_fail = 0;
      automatic logic [SECTION_WIDTH-1:0] concurrent_read_data;
      automatic logic [SECTION_WIDTH-1:0] concurrent_write_data = ~kernel_stim[1];

      // Initialize only the two kernel sections used by this test.
      write_kernel_section(5'd0, 2'd0, kernel_stim[0]);
      write_kernel_section(5'd0, 2'd1, kernel_stim[1]);

      // Assert both requests together. Each port will complete on its own clock.
      @(posedge RCK);
      @(posedge WCK);
      COMPE = 1'b0;
      RA = {5'd0, 2'd0}; RCSN = 1'b0;
      WA = {5'd0, 2'd1}; D = concurrent_write_data; M = '1;
      WCSN = 1'b0; WEN = 1'b0; FCSN = 1'b1;

      fork
        begin
          @(posedge RCK); #ApplTime;
          concurrent_read_data = Q;
          RCSN = 1'b1;
        end
        begin
          @(posedge WCK); #ApplTime;
          WCSN = 1'b1; WEN = 1'b1; D = '0;
        end
      join

      if (concurrent_read_data !== kernel_stim[0]) begin
        $error("[TB] Test4 concurrent Q read mismatch: got 0x%h, expected 0x%h",
               concurrent_read_data, kernel_stim[0]);
        test_fail++;
      end

      // Verify the concurrent write through Q, then restore original data.
      read_kernel(5'd0, 2'd1, rd_data);
      if (rd_data !== concurrent_write_data) begin
        $error("[TB] Test4 concurrent write mismatch: got 0x%h, expected 0x%h",
               rd_data, concurrent_write_data);
        test_fail++;
      end
      write_kernel_section(5'd0, 2'd1, kernel_stim[1]);
      read_kernel(5'd0, 2'd1, rd_data);
      if (rd_data !== kernel_stim[1]) begin
        $error("[TB] Test4 restore mismatch: got 0x%h, expected 0x%h",
               rd_data, kernel_stim[1]);
        test_fail++;
      end

      if (test_fail == 0) begin $display("[TB] Test 4: PASS"); pass_count++; end
      else                begin $display("[TB] Test 4: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST4

`ifdef tb_dimc_TEST5
    // =======================================================================
    // TEST 5: FULL MATRIX-VECTOR MULTIPLICATION (32 rows, compute_mask=0)
    // =======================================================================
    // Purpose: Verify full unmasked multiplication for all 32 kernel rows.
    // Verification: Load kernel/feature data and compare PSOUT and SOUT with golden values.
    // =======================================================================
    reset_dimc();
    write_full_kernel(kernel_stim);
    load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);
    $display("[TB] Test 5: loading feature vector + Full matrix-vector multiplication (32 rows)");
    begin
      automatic int test_fail = 0;
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        compute_and_capture(5'(r), BIAS, 10'd0, 2'b00, 2'b11,psout, clipped);
        // Check both the raw psum and clipped output independently.
        if (psout !== golden_psout[r] || clipped !== golden_clipped[r]) begin
          if (psout !== golden_psout[r])
            $error("[TB] Test5 row%0d: psout got 0x%08h, expected 0x%08h", r, psout, golden_psout[r]);
          if (clipped !== golden_clipped[r])
            $error("[TB] Test5 row%0d: clipped got %0d, expected %0d", r, clipped, golden_clipped[r]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 5: PASS"); pass_count++; end
      else                begin $display("[TB] Test 5: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST5

`ifdef tb_dimc_TEST6
    // =======================================================================
    // TEST 6: PIPELINED FULL MATRIX-VECTOR MULTIPLICATION
    // =======================================================================
    // Purpose: Verify one pipelined computation request per cycle.
    // Verification: Compare all 32 consecutive PSOUT and SOUT results with golden values.
    // =======================================================================
    $display("[TB] Test 6: Pipelined full matrix-vector multiplication (32 rows)");
    begin
      automatic int test_fail = 0;
      reset_dimc();
      write_full_kernel(kernel_stim);
      load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);
      compute_all_rows_pipelined(BIAS, 10'd0, 2'b00, 2'b11, psout_pipe, clipped_pipe);
      for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
        if (psout_pipe[r] !== golden_psout[r] || clipped_pipe[r] !== golden_clipped[r]) begin
          if (psout_pipe[r] !== golden_psout[r])
            $error("[TB] Test6 row%0d: psout got 0x%08h, expected 0x%08h",
                   r, psout_pipe[r], golden_psout[r]);
          if (clipped_pipe[r] !== golden_clipped[r])
            $error("[TB] Test6 row%0d: clipped got %0d, expected %0d",
                   r, clipped_pipe[r], golden_clipped[r]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 6: PASS"); pass_count++; end
      else                begin $display("[TB] Test 6: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST6

`ifdef tb_dimc_TEST7
    // =======================================================================
    // TEST 7: compute_mask MASKING SWEEP
    // =======================================================================
    // Purpose: Verify compute_mask behavior for six mask values on kernel row 0.
    // Verification: Compare masked PSOUT and SOUT results with their golden values.
    // =======================================================================
    $display("[TB] Test 7: compute-mask sweep (%0d values, row 0)", NB_COMPUTE_MASK_VALS);
    begin
      automatic logic [31:0] psout;
      automatic logic [7:0]  clipped;

      automatic int test_fail = 0;
      reset_dimc();
      for (int s = 0; s < 4; s++)
        write_kernel_section(5'd0, 2'(s), kernel_stim[s]);
      load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);
      for (int m = 0; m < NB_COMPUTE_MASK_VALS; m++) begin
        compute_and_capture(5'd0, BIAS, COMPUTE_MASK_VALS[m], 2'b00, 2'b11, psout, clipped);
        if (psout !== golden_psout_compute_mask[m] || clipped !== golden_compute_mask[m]) begin
          if (psout !== golden_psout_compute_mask[m])
            $error("[TB] Test7 compute_mask=%0d row0: psout got 0x%08h, expected 0x%08h",
                   COMPUTE_MASK_VALS[m], psout, golden_psout_compute_mask[m]);
          if (clipped !== golden_compute_mask[m])
            $error("[TB] Test7 compute_mask=%0d: clipped got %0d, expected %0d",
                   COMPUTE_MASK_VALS[m], clipped, golden_compute_mask[m]);
          test_fail++;
        end
      end
      if (test_fail == 0) begin $display("[TB] Test 7: PASS"); pass_count++; end
      else                begin $display("[TB] Test 7: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST7

`ifdef tb_dimc_TEST8
    // =======================================================================
    // TEST 8: SIGNED 8-BIT MULTIPLICATION
    // =======================================================================
    // Purpose: Verify sign_8b modes 01, 10, and 11 for all kernel rows.
    // Verification: Compare PSOUT and SOUT with sign_mode-specific golden values.
    // =======================================================================
    $display("[TB] Test 8: Signed 8-bit multiplication");
    begin
      automatic int test_fail = 0;
      automatic logic [31:0] expected_psout;
      automatic logic [7:0] expected_clipped;

      reset_dimc();
      write_full_kernel(kernel_stim);
      load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);

      for (int sign_mode = 1; sign_mode <= 3; sign_mode++) begin
        for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
          compute_and_capture(5'(r), BIAS, 10'd0, 2'(sign_mode), 2'b11, psout, clipped);

          case (sign_mode)
            1: begin expected_psout = golden_sign_01_psout[r]; expected_clipped = golden_sign_01_clipped[r]; end
            2: begin expected_psout = golden_sign_10_psout[r]; expected_clipped = golden_sign_10_clipped[r]; end
            3: begin expected_psout = golden_sign_11_psout[r]; expected_clipped = golden_sign_11_clipped[r]; end
          endcase

          if (psout !== expected_psout || clipped !== expected_clipped) begin
            if (psout !== expected_psout)
              $error("[TB] Test8 sign_8b=%02b row%0d: PSOUT got 0x%08h, expected 0x%08h",
                     sign_mode[1:0], r, psout, expected_psout);
            if (clipped !== expected_clipped)
              $error("[TB] Test8 sign_8b=%02b row%0d: SOUT got 0x%02h, expected 0x%02h",
                     sign_mode[1:0], r, clipped, expected_clipped);
            test_fail++;
          end
        end
      end

      if (test_fail == 0) begin $display("[TB] Test 8: PASS"); pass_count++; end
      else                begin $display("[TB] Test 8: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST8


`ifdef tb_dimc_TEST9
    // =======================================================================
    // TEST 9: multiplication with 1-bit, 2-bit and 4-bit precisions
    // =======================================================================
    // Purpose: Verify modes of 1-bit, 2-bit, 4-bit precision for all kernel rows.
    // Verification: Compare PSOUT and SOUT with precision-specific golden values.
    // =======================================================================
    $display("[TB] Test 9: multiplication with 1-bit, 2-bit and 4-bit precisions");
    begin
      automatic int test_fail = 0;
      automatic logic [31:0] expected_psout;
      automatic logic [7:0] expected_clipped;

      reset_dimc();
      write_full_kernel(kernel_stim);
      load_feature(feature_stim[0], feature_stim[1], feature_stim[2], feature_stim[3]);

      for (int mode = 0; mode < 3; mode++) begin
        for (int r = 0; r < NB_KERNEL_ROWS; r++) begin
          compute_and_capture(5'(r), BIAS, 10'd0, 2'b00, 2'(mode), psout, clipped);

          case (mode)
            0: begin expected_psout = golden_mode_00_psout[r]; expected_clipped = golden_mode_00_clipped[r]; end
            1: begin expected_psout = golden_mode_01_psout[r]; expected_clipped = golden_mode_01_clipped[r]; end
            2: begin expected_psout = golden_mode_10_psout[r]; expected_clipped = golden_mode_10_clipped[r]; end
          endcase

          if (psout !== expected_psout || clipped !== expected_clipped) begin
            if (psout !== expected_psout)
              $error("[TB] Test9 mode=%02b row%0d: PSOUT got 0x%08h, expected 0x%08h",
                     mode[1:0], r, psout, expected_psout);
            if (clipped !== expected_clipped)
              $error("[TB] Test9 mode=%02b row%0d: SOUT got 0x%02h, expected 0x%02h",
                     mode[1:0], r, clipped, expected_clipped);
            test_fail++;
          end
        end
      end

      if (test_fail == 0) begin $display("[TB] Test 9: PASS"); pass_count++; end
      else                begin $display("[TB] Test 9: FAIL (%0d mismatches)", test_fail); fail_count++; end
    end
`endif // tb_dimc_TEST9



    // FINAL SUMMARY
    $display("[TB] ================================================");
    $display("[TB] RESULTS: %0d PASSED, %0d FAILED", pass_count, fail_count);
    $display("[TB] ================================================");
    if (fail_count == 0) $display("[TB] ALL TESTS PASSED");
    else                  $display("[TB] FAILURES DETECTED");
    $display("Testbench: Test finished.");
    eot = 1'b1;   // signal completion to any external watcher
    $finish;
  end

  // WAVEFORM DUMP
  initial begin
    $dumpfile("sim/tb_dimc.vcd");
    $dumpvars(0, tb_dimc);
  end


  /** WATCHDOG TIMER **/
  // Kills the simulation after 50 µs (5000 clock cycles at 100 MHz).
  // trip always indicates a bug.
  initial begin
    #(5000 * ClkPeriod);
    $error("[TB] WATCHDOG: simulation exceeded 50 us");
    $finish;
  end

endmodule
